image: docker:stable

stages:
  - build

services:
  - docker:dind

build and push to registry:
  stage: build
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t victorcmoura/python-watchtower-deployable .
    - docker push victorcmoura/python-watchtower-deployable